// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "src/utils/prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  }
});
